apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service-depl
spec:
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: basantxbs/mypet:content
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2255
---
apiVersion: v1
kind: Service
metadata:
  name: content-service-clusterip-srv
spec:
  selector:
    app: content-service
  ports:
    - name: content-service
      protocol: TCP
      port: 3001
      targetPort: 3001


