apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-service-depl
spec:
  selector:
    matchLabels:
      app: partner-service
  template:
    metadata:
      labels:
        app: partner-service
    spec:
      containers:
      - name: partner-service
        image: basantxbs/mypet:partner
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2255
---
apiVersion: v1
kind: Service
metadata:
  name: partner-service-clusterip-srv
spec:
  selector:
    app: partner-service
  ports:
    - name: partner-service
      protocol: TCP
      port: 3002
      targetPort: 3002


